version: '3.8'

services:
  langgraph-app:
    build: .
    container_name: langgraph-news-agent
    ports:
      - "8000:8000"
    volumes:
      # 開発時にホットリロード用にソースコードをマウント
      - .:/app
      # node_modulesやvenvディレクトリは除外
      - /app/venv
      - /app/__pycache__
    environment:
      # 環境変数ファイルから読み込み（.envファイルがある場合）
      - ENV_FILE=.env
    env_file:
      - .env
    restart: unless-stopped
    # 開発モードで起動（ホットリロード有効）
    command: ["langgraph", "dev", "--host", "0.0.0.0", "--port", "8000"]
    
  # 本番環境用の設定例（コメントアウト）
  # langgraph-prod:
  #   build: .
  #   container_name: langgraph-news-agent-prod
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - ENV=production
  #   env_file:
  #     - .env.prod
  #   restart: unless-stopped
  #   command: ["langgraph", "start", "--host", "0.0.0.0", "--port", "8000"]
